services:
    app.admin.people:
        class: AppBundle\Admin\PeopleAdmin
        arguments: [~, AppBundle\Entity\People, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: People }
        public: true
